# services:
#   api:
#     build: .
#     container_name: fastapi_outfit
#     ports:
#       - "8001:8001"
#     volumes:
#       - .:/app
#     environment:
#       - PYTHONUNBUFFERED=1
#     restart: unless-stopped
services:
  api:
    image: wildandw/fastapi-outfit:latest
    container_name: fastapi_outfit
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped